### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by limelect** [mesutde/Delphi-Youtube-Downloader#1]
Compiled with D10.2.3 AND WINDOWS 7 !!!!!
And see mine
https://limelect.com/downloads/youtube_downloader_shell/

Process_win.inc line 284 PName=nil  FEnv=nil  PDir=nil  FApplicationName=''
FCommandLine=''
cmd
'"G:\Delphi Projects\mesutde\Delphi-Youtube-Downloader-main\Win32\Debug\Tools\yt-dlp.exe" -F https://www.youtube.com/watch?v=MqBu-lEPKWg&list=PLa9NT--jGmptDvxl8lJtzrAVUIeLAxEeN'
FCreationFlags=40
Gave as much as possible information
![image](https://github.com/user-attachments/assets/26cc8944-f342-4ea0-a6e9-203cdc631a5d)

**Comment by limelect** [comment]
Plz put ALL necessary files in your zip
yt-dlp.exe was missing I downloaded it but now

![image](https://github.com/user-attachments/assets/088de5f7-5a0c-454a-8945-3089478d6b43)

**Comment by limelect** [comment]
Ok i downloaded  yt-dlp 2024.09.27 and it works but missing
ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
which I have
However on this 
https://www.youtube.com/watch?v=ELhx5L5PiS8&list=LL&index=2&t=92s
no video only audio
I think I did enough debugging for you

**Comment by limelect** [comment]
You mix German and English

**Comment by mesutde** [comment]
![image](https://github.com/user-attachments/assets/9cb50ee1-6b5e-4407-8ddb-ae66959b24ae)
https://www.mediafire.com/file/agslbe2y717o23y/Delphi+Youtube+Downloader.zip/file

**Comment by limelect** [comment]
Your problems
1. you should put all files for everybody
2.  on this link  https://www.youtube.com/watch?v=XAkFQ-Nt7_c
     your software stack does not download
3.  My compilation works yours does not.
4. Putting all your files in my exe works but with final errors
5. The above link does not open the video buttons only the mp3
6. My ONLY 3 files mpeg mplay and probe they work
7. do not forget I work with window 7

![image](https://github.com/user-attachments/assets/54d39149-7a64-4f89-9639-1ef91f1cb274)
8 sometimes the green downloading works sometime no
9. to work you need ONLY 3 FILES no need for DLL.

**Comment by limelect** [comment]
![image](https://github.com/user-attachments/assets/9f356c2d-e20b-4d81-bbbf-eb71f3473ac3)

**Comment by limelect** [comment]
This is what happens on this link
![image](https://github.com/user-attachments/assets/c2bbae80-99d4-493a-9140-54f9d9c36b76)

**Comment by mesutde** [comment]
![image](https://github.com/user-attachments/assets/c01db090-416a-4983-8445-3daec874f71d)
I'm currently downloading a video that you can't download. First, improve yourself, then contribute to others. Have a good day.
